name: Publish Desktop
on: workflow_dispatch

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      package_version: ${{ steps.get-version.outputs.package_version }}
      release_id: ${{ steps.create-release.outputs.id }}
      tag_name: ${{ steps.get-version.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get Version
        id: get-version
        run: |
          PACKAGE_VERSION=$(node -p "require('./desktop/package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=DevPod-v$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            console.log("${{ steps.get-version.outputs.tag_name }}")
            
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ steps.get-version.outputs.tag_name }}",
              name: `DevPod v${process.env.PACKAGE_VERSION}`,
              body: 'Take a look at the assets to download and install DevPod Desktop',
              draft: true,
              prerelease: false
            })
            core.setOutput("id", data.id)

  build-app:
    needs: create-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          # - host: macos-latest
          #   target: x86_64-apple-darwin
          #   os: darwin
          #   arch: amd64
          # - host: macos-latest
          #   target: aarch64-apple-darwin
          #   os: darwin
          #   arch: arm64
          # The WIX version we use for the installer (latest 3.something) doesn't support arm builds - if we need to support arm windows,
          # we'd need to switch the installer toolchain to WIX 4.xx, not sure how that works out with tauri
          # - host: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   arch: arm64
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            arch: amd64
          # - host: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   os: linux
          #   arch: amd64
    name: ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    env:
      GO111MODULE: on
      GOFLAGS: -mod=vendor

    steps:
      - name: Check variables
        run: |
          echo "release id: [${{ needs.create-release.outputs.release_id }}]"
          echo "package version: [${{ needs.create-release.outputs.package_version }}]"
          echo "upload url: [${{ needs.create-release.outputs.upload_url }}]"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup System Dependencies
        if: matrix.settings.host == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./desktop/src-tauri -> target"

      - name: Go setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build Sidecar CLI
        if: matrix.settings.host != 'windows-latest'
        run: |
          BIN_NAME=devpod-cli-${{ matrix.settings.target }}
          GOOS=${{ matrix.settings.os }} GOARCH=${{ matrix.settings.arch }} go build -ldflags "-s -w" -o "test/$BIN_NAME"
          cp "test/$BIN_NAME" "desktop/src-tauri/bin/$BIN_NAME"
          ls desktop/src-tauri/bin

      - name: Build Sidecar CLI
        if: matrix.settings.host == 'windows-latest'
        shell: cmd
        run: |
          set GOOS=windows
          set GOARCH=${{ matrix.settings.arch }}
          set BIN_NAME=devpod-cli-${{ matrix.settings.target }}.exe

          go build -ldflags "-s -w" -o "test/%BIN_NAME%"

          xcopy /F /Y "test\%BIN_NAME%" desktop\src-tauri\bin\*

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: "./desktop/yarn.lock"

      - name: Install frontend dependencies
        run: yarn install
        working-directory: "./desktop"

      - name: Build Desktop App
        if: matrix.settings.host != 'windows-latest'
        uses: tauri-apps/tauri-action@dev
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}
          projectPath: "./desktop"
          args: " --target ${{ matrix.settings.target }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # MacOS Signing:
          # ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          # APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          # APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          # APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          #
          # AppImage Signing:
          SIGN: ${{ secrets.APP_IMAGE_SIGN }}
          SIGN_KEY: ${{ secrets.APP_IMAGE_SIGN_KEY }}
          APPIMAGETOOL_SIGN_PASSPHRASE: ${{ secrets.APP_IMAGE_SIGN_PASSPHRASE }}

      - name: Build Desktop App
        if: matrix.settings.host == 'windows-latest'
        id: build-desktop-app
        uses: tauri-apps/tauri-action@dev
        with:
          projectPath: "./desktop"
          args: " --target ${{ matrix.settings.target }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign Windows App
        if: matrix.settings.host == 'windows-latest'
        shell: powershell
        env:
          CODESIGNTOOL_USERNAME: ${{ secrets.CODESIGNTOOL_USERNAME }}
          CODESIGNTOOL_PASSWORD: ${{ secrets.CODESIGNTOOL_PASSWORD }}
          CODESIGNTOOL_TOTP_SECRET: ${{ secrets.CODESIGNTOOL_TOTP_SECRET }}
          CODESIGNTOOL_CREDENTIAL_ID: ${{ secrets.CODESIGNTOOL_CREDENTIAL_ID }}
          CODESIGNTOOL_DOWNLOAD_URL: ${{ vars.CODESIGNTOOL_DOWNLOAD_URL }}
          CODESIGNTOOL_FILE_PATH: desktop\src-tauri\target\${{ matrix.settings.target }}\release\bundle\msi\DevPod_${{ needs.create-release.outputs.package_version }}_x64_en-US.msi
        run: |
          $username = "$Env:CODESIGNTOOL_USERNAME"
          $password = "$Env:CODESIGNTOOL_PASSWORD"
          $totp_secret = "$Env:CODESIGNTOOL_TOTP_SECRET"
          $credential_id = "$Env:CODESIGNTOOL_CREDENTIAL_ID"
          $download_url = "$Env:CODESIGNTOOL_DOWNLOAD_URL"
          $input_file_path = "$Env:CODESIGNTOOL_FILE_PATH"

          Write-Output "Starting to download CodeSignTool from $download_url"

          Invoke-WebRequest -Uri $download_url -OutFile codesigntool.zip

          $destination_path = "codesigntool"
          Write-Output "Unzipping to $destination_path"
          Expand-Archive "codesigntool.zip" -DestinationPath $destination_path 

          Set-Location -Path $destination_path
          Set-Location -Path (Get-ChildItem -Path . -Include CodeSignTool* | %{$_.FullName})

          cmd.exe /c ".\CodeSignTool.bat" sign -username="$username" -password="$password" -totp_secret="$totp_secret" -credential_id="$credential_id" -input_file_path="..\..\$input_file_path" -override

      - name: Check Dir
        if: matrix.settings.host == 'windows-latest'
        shell: bash
        run: |
          ls ./desktop/src-tauri/target/${{ matrix.settings.target }}/release/bundle/msi
          
      - name: Upload Release Asset
        if: matrix.settings.host == 'windows-latest'
        run: |
          gh release upload ${{ needs.create-release.outputs.tag_name }} desktop/src-tauri/target/${{ matrix.settings.target }}/release/bundle/msi/DevPod_${{ needs.create-release.outputs.package_version }}_x64_en-US.msi --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
